<#
.SYNOPSIS
    Interactive setup wizard for Agent OS — guides you through personalizing
    your agent's profile, running the Bridge setup, and generating the
    system prompt.

.DESCRIPTION
    Asks a series of questions about:
    - Relationship (friend? assistant? companion? mentor?)
    - Communication style (formal? casual? how to address you?)
    - Primary use cases (coding? chat? study? work?)
    - Preferences (concise answers? code samples?)
    - Taboos (things the agent should never do)

    Then generates my_profile.md and runs Bridge setup.

.EXAMPLE
    .\scripts\setup_wizard.ps1
#>

[CmdletBinding()]
param()

Set-StrictMode -Version Latest

$agentHome = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$profilePath = Join-Path $agentHome "my_profile.md"

Write-Host ""
Write-Host "╔══════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║      Agent OS - Setup Wizard             ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""
Write-Host "Let's get to know each other so your agent can be truly yours."
Write-Host "You can leave any answer blank to skip."
Write-Host ""

function Ask-Question($prompt, $default) {
    if ($default) {
        $answer = Read-Host "${prompt} (${default})"
        if ([string]::IsNullOrWhiteSpace($answer)) { return $default }
    } else {
        $answer = Read-Host $prompt
    }
    return $answer
}

function Ask-MultiLine($prompt) {
    Write-Host $prompt -ForegroundColor Yellow
    $lines = @()
    while ($true) {
        $line = Read-Host "  >"
        if ([string]::IsNullOrWhiteSpace($line)) { break }
        $lines += $line
    }
    if ($lines.Count -eq 0) { return "" }
    return $lines -join "`n"
}

# --- Relationship ---
Write-Host "`n--- Relationship ---" -ForegroundColor Green
Write-Host "What role should the agent play in your life?"
$role = Ask-Question "  Role (friend/assistant/companion/mentor/partner)" "friend"
$name = Ask-Question "  What should the agent call you?" "you"
$relationshipDesc = Ask-MultiLine "  Describe your relationship in your own words:"

# --- Communication style ---
Write-Host "`n--- Communication Style ---" -ForegroundColor Green
$tone = Ask-Question "  Tone (formal/casual/warm/playful)" "warm"
$address = Ask-Question "  How should the agent address you? (e.g. 亲爱的, boss, nothing)" "亲爱的"
$verbosity = Ask-Question "  Verbosity (concise/balanced/detailed)" "concise"

# --- Primary use ---
Write-Host "`n--- Primary Use ---" -ForegroundColor Green
$useCases = Ask-MultiLine "  What do you mainly want the agent to help with? (one per line, blank to finish)"

# --- Preferences ---
Write-Host "`n--- Preferences ---" -ForegroundColor Green
$preferences = Ask-MultiLine "  Any specific preferences? (e.g. answer in Chinese, always show code, etc.)"

# --- Taboos ---
Write-Host "`n--- Taboos ---" -ForegroundColor Green
$taboos = Ask-MultiLine "  Anything the agent should absolutely NOT do? (blank to skip)"

# --- Generate profile ---
Write-Host "`nGenerating your profile..." -ForegroundColor Yellow

$content = @"
# My Agent Profile

> Generated by setup_wizard.ps1 on $(Get-Date -Format "yyyy-MM-dd")

## Relationship

**Role**: $role
**Name**: $name
$((if ($relationshipDesc) { "**Description**:`n$relationshipDesc" } else { "" }))

## Communication Style

- **Tone**: $tone
- **Address**: $address
- **Verbosity**: $verbosity

## Primary Use

$((if ($useCases) { $useCases -split "`n" | ForEach-Object { "- $_" } | Out-String } else { "- Not specified yet" }))

## Preferences

$((if ($preferences) { $preferences -split "`n" | ForEach-Object { "- $_" } | Out-String } else { "- None specified" }))

## Taboos

$((if ($taboos) { $taboos -split "`n" | ForEach-Object { "- $_" } | Out-String } else { "- None specified" }))
"@

Set-Content -LiteralPath $profilePath -Value $content -Encoding UTF8
Write-Host "  Profile saved to: $profilePath" -ForegroundColor Green

# --- Offer to run Bridge setup ---
Write-Host "`n--- Bridge Setup ---" -ForegroundColor Green
$runBridge = Read-Host "  Run Bridge setup now? (Y/n)"
if ($runBridge -eq "" -or $runBridge -eq "y" -or $runBridge -eq "Y") {
    $bridgeSetup = Join-Path (Join-Path $agentHome "Bridge") "setup.ps1"
    if (Test-Path -LiteralPath $bridgeSetup) {
        Write-Host "  Running Bridge setup..." -ForegroundColor Yellow
        & $bridgeSetup
    } else {
        Write-Host "  Bridge setup not found at: $bridgeSetup" -ForegroundColor Red
    }
}

Write-Host ""
Write-Host "╔══════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║      Setup Complete!                      ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""
Write-Host "Your agent profile is ready. The agent will read it at startup."
Write-Host ""
Write-Host "Next: configure your AI client's system prompt to include:"
Write-Host "  - The contents of Bridge\Agent-Bootstrap-Prompt.md"
Write-Host "  - The generated system prompt from dist\agent_system_prompt.md"
Write-Host ""
